### ISSUE TITLE
[Bug] ModelEnsembleStatementVerifier: tensors on different devices

### ISSUE THREAD

**Issue by NiklasTUM** [lukasellinger/evaluating-word-definitions#1]
When selecting the ModelEnsembleStatementVerifier as the statement verification model, an error occurs that indicates that not all tensors are on the same device. This is the corresponding error log:

2024-12-02 14:28:07,075 WARNING: <All keys matched successfully>
/home/mushroom/mu-shroom-hallucination-detection/venv/lib/python3.12/site-packages/torch/nn/modules/linear.py:125: UserWarning: Attempting to use hipBLASLt on an unsupported architecture! Overriding blas backend to hipblas (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:296.)
  return F.linear(input, self.weight, self.bias)
Traceback (most recent call last):
  File "/home/mushroom/.cache/JetBrains/RemoteDev/dist/dc51b8de7aeac_pycharm-professional-242.23726.56/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mushroom/.cache/JetBrains/RemoteDev/dist/dc51b8de7aeac_pycharm-professional-242.23726.56/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mushroom/mu-shroom-hallucination-detection/src/kg_hallucination_detector.py", line 526, in <module>
    hallucinated_spans = hallucination_detector.detect_hallucinated_spans(question, original_answer)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mushroom/mu-shroom-hallucination-detection/src/kg_hallucination_detector.py", line 474, in detect_hallucinated_spans
    reference_answers = self.generate_reference_answers(question, original_answer)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mushroom/mu-shroom-hallucination-detection/src/kg_hallucination_detector.py", line 74, in generate_reference_answers
    result = self.fact_checker_pipeline.verify(search_term, original_answer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mushroom/mu-shroom-hallucination-detection/evaluating-word-definitions/pipeline_module/pipeline.py", line 117, in verify
    return self.verify_batch([entry], only_intro=only_intro)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mushroom/mu-shroom-hallucination-detection/evaluating-word-definitions/pipeline_module/pipeline.py", line 92, in verify_batch
    factualities = self.stm_verifier(processed_batch, evids_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mushroom/mu-shroom-hallucination-detection/evaluating-word-definitions/pipeline_module/statement_verifier.py", line 24, in __call__
    return self.verify_statement_batch(statements, evidence_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mushroom/mu-shroom-hallucination-detection/evaluating-word-definitions/pipeline_module/statement_verifier.py", line 210, in verify_statement_batch
    combined_probabilities = 1.5 * probabilities[
                             ^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
python-BaseException

**Comment by lukasellinger** [comment]
fixed it in the [latest commit](https://github.com/lukasellinger/evaluating-word-definitions/commit/aaed9155af522f4843d8a54922a8b30c7e16eaaa) 

Please note that the ModelStatementVerifier is primarily an experimental artifact I tested with.

**Comment by NiklasTUM** [comment]
Thanks for the quick fix! It works now as expected.
